package pl.polsl.lab.servlets;

import javax.servlet.*;
import javax.servlet.http.*;
import java.io.*;
import java.util.*;

/**
 * Main class of the servlet displaying current time, date and image. Site
 * generated by servlet is refreshed every 10 seconds.
 *
 * @author Gall Anonim
 * @version 1.0
 */
public class First extends HttpServlet { 

    /**
     * Handles the HTTP <code>GET</code> method.
     *
     * @param req servlet request
     * @param resp servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    public void doGet(HttpServletRequest req, HttpServletResponse resp)
            throws ServletException, IOException {
        // Response type
        resp.setContentType("text/html; charset=ISO-8859-2");

        // Stream containing generated response
        PrintWriter out = resp.getWriter();

        // Header type -> refresh every 10 sec
        resp.setHeader("Refresh", "1");

        // Current date and time
        String date = new Date().toString();

        out.println("<html>\n<body>\n" + date + "\n<h1>Hello !!!</h1><br>\n"
                + "<img border=\"0\" src=\"" + req.getContextPath()
                + "/images/duke.thumbsup.gif\">\n</body>\n</html>");
    }

    /**
     * Handles the HTTP <code>POST</code> method.
     *
     * @param req servlet request
     * @param resp servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    public void doPost(HttpServletRequest req, HttpServletResponse resp)
            throws ServletException, IOException {
        doGet(req, resp);
    }
}
