#pragma once
enum TextDesc {FILE_INFO, THREAD_INFO, DLL_INFO, TIME_INFO, TIME_VALUE};

enum ControlType {CONTROL_NONE, CONTROL_BACK, CONTROL_NEXT, CONTROL_FILE, CONTROL_SLIDER, CONTROL_RADIO_BUTTONS, CONTROL_RUN};

enum DllChoice {DLL_ASM, DLL_C};